---
version: 1
enabled: true
plugins:
  job_runtime:
    enabled: true
  auto_upload:
    enabled: true
    auto_upload: true
#  static_hosting:
#    your_unique_id:
#      metadata:
#        name: "Name of artifact you're hosting, such as Code Coverage Report"
#      path: path/from/git/root/to/directory/to/host
