---
version: 1
enabled: true
plugins:
  job_runtime:
    enabled: true
  auto_upload:
    enabled: true
    auto_upload: true
  static_hosting:
    test_results:
      metadata:
        name: Test Results
      path: .report/test_report.html
    test_coverage:
      metadata:
        name: Test Coverage
      path: htmlcov/
    mypy_report:
      metadata:
        name: Mypy Report
      path: .report/mypy-report/
