---
version: 1
enabled: true
plugins:
  job_runtime:
    enabled: true
  static_hosting:
    test_results:
      path: .report/test_report.html
    test_coverage:
      path: htmlcov/
    mypy_report:
      path: .report/mypy-report/
    flake8_report:
      path: .report/flake8/
    site_preview:
      path: site/
  metric:
    site_preview_size:
      filename: site_preview_size.csv
  chart:
    site_preview_size_chart:
      title: Site Preview Size
      y_title: Size (bytes)
      tags:
        - site_preview_size
  workflow_dispatch:
    test-workflow-dispatch:
      filename: test-workflow-dispatch.yml
