---
version: 1
enabled: true
plugins:
  job_runtime:
    enabled: true
  auto_upload:
    enabled: true
    auto_upload: true
  static_hosting:
    test_results:
      metadata:
        name: Test Results
      path: .report/test_report.html
    test_coverage:
      metadata:
        name: Test Coverage
      path: htmlcov/
    mypy_report:
      metadata:
        name: Mypy Report
      path: .report/mypy-report/
    flake8_report:
      metadata:
        name: Flake8 Report
      path: .report/flake8/
    site_preview:
      metadata:
        name: Site Preview
      path: site/
  metric:
    site_preview_size:
      filename: site_preview_size.csv
  chart:
    site_preview_size_chart:
      title: Site Preview Size
      y_title: Size (bytes)
      tags:
        - site_preview_size
  workflow_dispatch:
    test:
      filename: test-workflow-dispatch.yml
      identifier: workflow_test.${{ github.event.inputs.workflow_run_identifier }}
